name: db_helper
description: Database Helper.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  path: ^1.8.0
  path_provider: ^2.0.0
  sqflite: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
